on: [release]

name: Deploy to Web App for Containers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: slalomdevops.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t slalomdevops.azurecr.io/nodeapp:${{ github.sha }}
        docker push slalomdevops.azurecr.io/nodeapp:${{ github.sha }} 
      
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'node-rnc'
        images: 'slalomdevops.azurecr.io/nodeapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
